### ISSUE TITLE
Differences between CogVideoXDPMScheduler and CogVideoXDDIMScheduler for cogvideo-X-1.5-I2V

### ISSUE THREAD

**Issue by hjrPhoebus** [a-r-r-o-w/finetrainers#120]
It seems that in training script, CogVideoXDPMScheduler is used for both training and validation. 

```scheduler = CogVideoXDPMScheduler.from_pretrained(args.pretrained_model_name_or_path, subfolder="scheduler")```

However, when using 
```pipe = CogVideoXImageToVideoPipeline.from_pretrained("CogVideoX1.5-5B-I2V", torch_dtype=torch.bfloat16)```
CogVideoXDDIMScheduler is used as can be seen from the diffusers ckpt file ```CogVideoX1.5-5B/scheduler/scheduler_config.json```
```
{
  "_class_name": "CogVideoXDDIMScheduler",
  "_diffusers_version": "0.32.0.dev0",
  "beta_end": 0.012,
  "beta_schedule": "scaled_linear",
  "beta_start": 0.00085,
  "clip_sample": false,
  "clip_sample_range": 1.0,
  "num_train_timesteps": 1000,
  "prediction_type": "v_prediction",
  "rescale_betas_zero_snr": true,
  "sample_max_value": 1.0,
  "set_alpha_to_one": true,
  "snr_shift_scale": 1.0,
  "steps_offset": 0,
  "timestep_spacing": "trailing",
  "trained_betas": null
}
```

Could you tell me what's the difference between these two schedulers? Thanks a lot.

**Comment by sayakpaul** [comment]
Ccing @zRzRzRzRzRzRzR from the Cog team for more details. But will close this as it's not directly related to `finetrainers`.
