### ISSUE TITLE
THUDM/cogvlm2-llama3-caption VRAM requirement OOM

### ISSUE THREAD

**Issue by wr0124** [a-r-r-o-w/finetrainers#122]
### Feature request  / 功能建议

I want to create video captions for my video dataset. Based on the page ["https://huggingface.co/THUDM/cogvlm2-llama3-caption"](https://huggingface.co/THUDM/cogvlm2-llama3-caption) which seems to be an excellent choice. However, it appears that this model requires a large amount of VRAM? I am using an A5000 (24GB VRAM). How much VRAM does this model require? Are there any settings that can be modified to run in on A5000 or several A5000 ?

### Motivation / 动机

hope to get solution

### Your contribution / 您的贡献

![Screenshot from 2024-12-12 18-06-02](https://github.com/user-attachments/assets/2e6f3b76-be9a-4cff-a4dd-fc4527203942)
![Screenshot from 2024-12-12 18-05-42](https://github.com/user-attachments/assets/beb736d9-fa02-4467-b385-3d71f7256c4a)
![Screenshot from 2024-12-12 18-06-02](https://github.com/user-attachments/assets/9fd55fff-71ff-427b-b96a-e3c31a27c99a)
![Screenshot from 2024-12-12 18-05-42](https://github.com/user-attachments/assets/578cfd24-1097-4217-9c2e-1f95af93e8f2)

**Comment by sayakpaul** [comment]
Hmm CogVLM seems to be a large model and you're likely better off with a 40GB card. Since it is not directly related to the `finetrainers` repo, I am going to close the issue.
