### ISSUE TITLE
LTX does not support SFT?

### ISSUE THREAD

**Issue by ootsuka-repos** [a-r-r-o-w/finetrainers#128]
Are there any plans to support SFT in LTX?
I know from the source that we currently support Lora for each OSS-video.

https://github.com/a-r-r-o-w/finetrainers/blob/9ef58e2f3a018aed73e83ef63ee85daf009a1a53/finetrainers/args.py#L367
help="Type of training to perform. Choose between ['lora']",

**Comment by a-r-r-o-w** [comment]
Full finetuning support will be added soon, yes!
