### ISSUE TITLE
HunyuanVideo CKPT?

### ISSUE THREAD

**Issue by Aristo23333** [a-r-r-o-w/finetrainers#134]
Hi author:
Thanks for your great work!
I find in hunyuan_video_lora.py you use huggingface transformers to load CKPT of HunyuanVideo. I find in original model it has no config file. I meet 'model_type' error when using your sh. Could you give me some advice? To load the CKPT?

**Comment by a-r-r-o-w** [comment]
The diffusers-format weights have not yet been merged unfortunately :(

https://huggingface.co/tencent/HunyuanVideo/discussions/18

Could you try passing `--revision refs/pr/18` and see if it works when launching the script?

**Comment by sayakpaul** [comment]
Can be closed as we have hosted https://huggingface.co/hunyuanvideo-community/HunyuanVideo.

**Comment by Aristo23333** [comment]
> Can be closed as we have hosted https://huggingface.co/hunyuanvideo-community/HunyuanVideo.
Thank you, it can work!

**Comment by Aristo23333** [comment]
> Can be closed as we have hosted https://huggingface.co/hunyuanvideo-community/HunyuanVideo.

But when I am trying to load your CKPT, I get OOM in my 80GB H800. In train.py trainer.oreoare_trainable_parameters 
![image](https://github.com/user-attachments/assets/1534feab-c3ad-43f9-b210-421a1b1cf4f9)

**Comment by sayakpaul** [comment]
Could you please open a new issue for this? Please also provide the exact training command you used.

**Comment by Aristo23333** [comment]
> Could you please open a new issue for this? Please also provide the exact training command you used.

I have open it https://github.com/a-r-r-o-w/finetrainers/issues/142 Thank you!
