### ISSUE TITLE
Bucketing Explained?

### ISSUE THREAD

**Issue by ArEnSc** [a-r-r-o-w/finetrainers#140]
### System Info / 系統信息

Hey, what is Bucketing's purpose and how does it work with the fine trainer's library and what does it do?

My thought from my experience in training is, it allows generalizing the number of frames and resolutions by exposing the model to different samples. Is this correct?
It supports different resolutions + durations through the number of frames.

My question surrounding this was, then what is the correct settings for LTXV ?
it seems like they say they support

24 FPS videos at 768x512
So the bucket sampler says more or less by default needs 2 second videos at that resolution, with this configuration 
 49x512x768?
 
Does this mean it will only use videos within that frame range and or truncate anything out of bounds of the number of frames?
I assume it if you add more parameters like so

17x512x768 49x512x768 61x512x768 129x512x768

It will find the closest number of frames for a sample then truncate the remainder or padd the remainder of frames correct?

Thanks
@a-r-r-o-w 

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

This is just a question

### Expected behavior / 期待表现

Answer to the question.

**Comment by a-r-r-o-w** [comment]
The purpose of bucketing is to enable batch_size > 1 training and allowing training only with some fixed resolutions and number of frames.

For example, setting it to `49x512x768 81x1024x1024` will round all your videos down to the nearest resolution/frame bucket. If a video has 60 frames, some of its in-between frames will be discarded to select a total of 49 frames uniformly, and resizing to `512x768` resolution will be performed. If a video has 80 frames, it will still be put in the 49 frame bucket. So, the behaviour is to find the closest smaller bucket size in which the video does not fit. Multiple videos put into same bucket can be combined together for a single forward pass, if batch size is greater than 1. There is no padding involved

If no smaller bucket size is compatible for a video (let's say, it has lesser number of frames than the smallest specified frame bucket size), it can either be discarded or used individually  based on some dataset CLI argumnets

**Comment by ArEnSc** [comment]
@a-r-r-o-w thanks for the explainer! much appreciated!
