### ISSUE TITLE
Bug for using train_text_to_video_lora.sh

### ISSUE THREAD

**Issue by JustinKai0527** [a-r-r-o-w/finetrainers#151]
### System Info / 系統信息

3090

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

I install this in my 3090
conda create -n cogvideox python=3.10
conda install pytorch==2.4.0 torchvision==0.19.0 torchaudio==2.4.0  pytorch-cuda=11.8 -c pytorch -c nvidia
pip install -r requirements.txt
pip install opencv-python
pip install imageio
and I using the text_to_video_lora.sh found that the NVML

UserWarning: Can't initialize NVML
  warnings.warn("Can't initialize NVML")
Traceback (most recent call last):
  File "/home/jasper0314/miniconda3/envs/cogvideox/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/home/jasper0314/miniconda3/envs/cogvideox/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 48, in main
    args.func(args)
  File "/home/jasper0314/miniconda3/envs/cogvideox/lib/python3.10/site-packages/accelerate/commands/launch.py", line 1146, in launch_command
    args, defaults, mp_from_config_flag = _validate_launch_command(args)
  File "/home/jasper0314/miniconda3/envs/cogvideox/lib/python3.10/site-packages/accelerate/commands/launch.py", line 980, in _validate_launch_command
    defaults = load_config_from_file(args.config_file)
  File "/home/jasper0314/miniconda3/envs/cogvideox/lib/python3.10/site-packages/accelerate/commands/config/config_args.py", line 46, in load_config_from_file
    raise FileNotFoundError(
FileNotFoundError: The passed configuration file accelerate_configs/uncompiled_1.yaml does not exist. Please pass an existing file to accelerate launch, or use the default one created through accelerate config and run accelerate launch without the --config_file argument.
-------------------- Finished executing script --------------------

and then I use nvidia-smi found that my gpu was got werid
nvidia-smi
Unable to determine the device handle for GPU0000:03:00.0: Unknown Error
and torch.cuda.is_available() got false
I only run the train_text_to_video.bash.....

### Expected behavior / 期待表现

don't got error

**Comment by JustinKai0527** [comment]
@a-r-r-o-w do you got this error

**Comment by JustinKai0527** [comment]
> @a-r-r-o-w do you got this error



> ### System Info / 系統信息
> 3090
> 
> ### Information / 问题信息
> * [x]  The official example scripts / 官方的示例脚本
> * [ ]  My own modified scripts / 我自己修改的脚本和任务
> 
> ### Reproduction / 复现过程
> I install this in my 3090 conda create -n cogvideox python=3.10 conda install pytorch==2.4.0 torchvision==0.19.0 torchaudio==2.4.0 pytorch-cuda=11.8 -c pytorch -c nvidia pip install -r requirements.txt pip install opencv-python pip install imageio and I using the text_to_video_lora.sh found that the NVML
> 
> UserWarning: Can't initialize NVML warnings.warn("Can't initialize NVML") Traceback (most recent call last): File "/home/jasper0314/miniconda3/envs/cogvideox/bin/accelerate", line 8, in sys.exit(main()) File "/home/jasper0314/miniconda3/envs/cogvideox/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 48, in main args.func(args) File "/home/jasper0314/miniconda3/envs/cogvideox/lib/python3.10/site-packages/accelerate/commands/launch.py", line 1146, in launch_command args, defaults, mp_from_config_flag = _validate_launch_command(args) File "/home/jasper0314/miniconda3/envs/cogvideox/lib/python3.10/site-packages/accelerate/commands/launch.py", line 980, in _validate_launch_command defaults = load_config_from_file(args.config_file) File "/home/jasper0314/miniconda3/envs/cogvideox/lib/python3.10/site-packages/accelerate/commands/config/config_args.py", line 46, in load_config_from_file raise FileNotFoundError( FileNotFoundError: The passed configuration file accelerate_configs/uncompiled_1.yaml does not exist. Please pass an existing file to accelerate launch, or use the default one created through accelerate config and run accelerate launch without the --config_file argument. -------------------- Finished executing script --------------------
> 
> and then I use nvidia-smi found that my gpu was got werid nvidia-smi Unable to determine the device handle for GPU0000:03:00.0: Unknown Error and torch.cuda.is_available() got false I only run the train_text_to_video.bash.....
> 
> ### Expected behavior / 期待表现
> don't got error

@a-r-r-o-w could you help me thx!!!!!

**Comment by a-r-r-o-w** [comment]
This seems like an environment error. I would recommend setting up CUDA 12.4 and Pytorch 2.5.1 compatible with that cuda version.

You can read more about it here: https://stackoverflow.com/questions/43022843/nvidia-nvml-driver-library-version-mismatch
