### ISSUE TITLE
Resume and reprod of reproducibility for Hunayuan 

### ISSUE THREAD

**Issue by Aristo23333** [a-r-r-o-w/finetrainers#156]
I notice that hunyuan finetuning script seems not support resume_from_checkpoint mehod and it is signed as "TODO". Do you plan to add this. Besides, I wonder how to use your inference API to generate the same results in finetuning validation by the checkpoint of finetuning? Thank you!

**Comment by a-r-r-o-w** [comment]
Support for this has been added in #139. Could you give it a try? Marking the issue as resolved, but if it does not work as expected, please do re-open and ping `@sayakpaul`
