### ISSUE TITLE
Support passing custom height and width for validation resolutions

### ISSUE THREAD

**Issue by a-r-r-o-w** [a-r-r-o-w/finetrainers#55]
When doing multi-resolution/frame training, validation only occurs for 49 x 720 x 480 videos. Since we support multiple prompts (`--validation_prompts`) and images as validation inputs (`--validation_images`) by making use of the `--validation_prompt_separator`, I think it also makes sense to support multiple resolutions via a `--validation_resolutions` parameter.

@zRzRzRzRzRzRzR @sayakpaul

**Comment by sayakpaul** [comment]
Yeah not a bad idea but the logic could get messy if I am envisioning it correctly. Better could be add a small note saying something like "since this trained using multiple resolutions, be sure to test it on multiple resolutions to confirm effectiveness."

**Comment by a-r-r-o-w** [comment]
Supported now in the trainer API with `{prompt}@@@49x480x720`. The part after `@@@` is the num_frames, height and width.
