### ISSUE TITLE
[question] what is the difference between cofgvideo scheduler and normal diffuers scheduler

### ISSUE THREAD

**Issue by foreverpiano** [a-r-r-o-w/finetrainers#82]
### Feature request  / 功能建议

CogVideoXDPMScheduler VS DPMSCheduler
CogVideoXDDIMScheduler VS DDIM Scheduler
Hi Aryan, is there any sampling difference between these two sampler? 
@a-r-r-o-w 

### Motivation / 动机

/

### Your contribution / 您的贡献

/

**Comment by a-r-r-o-w** [comment]
Hey. So the CogVideoX folks have a slightly different training objective compared to the original diffusion schedulers. The DDIMScheduler is the original formulation. The CogVideoXDDIMScheduler is the modified implementation from the CogVideoX folks - you can see that it is adapted from the https://github.com/THUDM/CogVideo repo.

**Comment by foreverpiano** [comment]
I see that the formula is same and now Cogvideo repo uses diffusers version. Do you mean the sampling object is different? I don't know what is the exact difference. I use the DDIMscheduler instead of CogVideoXDDIMScheduler and the result is bad.

**Comment by sayakpaul** [comment]
Gentle ping @a-r-r-o-w

**Comment by a-r-r-o-w** [comment]
@foreverpiano The underlying DDIM algorithm is the same, but the scaling factor for model output and latent sample is different between original and Cog implementation. The details are a bit hazy in my mind and I'm unsure where the motivation for this comes from, but IIRC from what I was explained, Cog uses a simpler update rule compared to original formulation. It does not make use of epsilon update to move toward x_0, but in DDIMScheduler the `pred_epsilon` is added as well, but the model is not conditioned with it, so it produces noisy generation (you only have to compare the `v-prediction` branches). @zRzRzRzRzRzRzR might be able to provide more information.

https://github.com/huggingface/diffusers/blob/c96bfa5c80eca798d555a79a491043c311d0f608/src/diffusers/schedulers/scheduling_ddim.py#L448

https://github.com/huggingface/diffusers/blob/c96bfa5c80eca798d555a79a491043c311d0f608/src/diffusers/schedulers/scheduling_ddim_cogvideox.py#L394

**Comment by sayakpaul** [comment]
I think Aryan's comment has answered this question. Will close as it is not directly related to `finetrainers`.
